spring:
  application: 
      name: product-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/tienda
    password: ivan1705
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update
eureka:
    instance:
      preferIpAddress: true
    client:
      fetchRegistry: true
      registerWithEureka: true
      serviceUrl:
        defaultZone: http://localhost:8761/eureka

server:
  port: 0